# Application configuration.
server:
  port: 8080

# Redis configuration.
## As we are running Redis on Docker we are setting up its configuration.
spring:
  redis:
    host: localhost
    port: 6379

init:
  fixture:
    account:
      path: /fixtures/accounts.json
      enabled: true
    transaction:
      path: /fixtures/transaction_deposit.json
      enabled: true

cache:
  account: ACCOUNT
  transaction: TRANSACTION
  index:
    account: INDEX_ACCOUNT
    transaction: INDEX_TRANSACTION
