# Application configuration.
server:
  port: 8080

# Redis configuration.
## As we are running Redis on Docker we are setting up its configuration.
spring:
  redis:
    host: localhost
    port: 6379

init:
  fixture:
    account:
      enabled: true
    transaction:
      enabled: true